language: cpp
dist: trusty
sudo: required
install: pwd && sudo add-apt-repository ppa:chris-lea/libsodium -y && sudo apt-get update && sudo apt-get install libsodium-dev && sudo apt-get update && sudo apt-get install -y build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libgtest-dev
script: make -j2
