language: cpp
sudo: required
install: sudo add-apt-repository ppa:chris-lea/libsodium -y && sudo apt-get update && sudo apt-get install -y build-essential cmake pkg-config libboost-all-dev libssl-dev libunbound-dev libsodium-dev libminiupnpc-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libgtest-dev
script: make -j2
